const BOOK_MAP: Record<string, string> = {
  "Genesis": "Genesi",
  "Exodus": "Esodo",
  "Leviticus": "Levitico",
  "Numbers": "Numeri",
  "Deuteronomy": "Deuteronomio",
  "Joshua": "Giosuè",
  "Judges": "Giudici",
  "Ruth": "Rut",
  "1 Samuel": "1 Samuele",
  "2 Samuel": "2 Samuele",
  "1 Kings": "1 Re",
  "2 Kings": "2 Re",
  "1 Chronicles": "1 Cronache",
  "2 Chronicles": "2 Cronache",
  "Ezra": "Esdra",
  "Nehemiah": "Neemia",
  "Esther": "Ester",
  "Job": "Giobbe",
  "Psalm": "Salmo",
  "Psalms": "Salmi",
  "Proverbs": "Proverbi",
  "Ecclesiastes": "Qoelet",
  "Song of Solomon": "Cantico dei Cantici",
  "Song of Songs": "Cantico dei Cantici",
  "Isaiah": "Isaia",
  "Jeremiah": "Geremia",
  "Lamentations": "Lamentazioni",
  "Ezekiel": "Ezechiele",
  "Daniel": "Daniele",
  "Hosea": "Osea",
  "Joel": "Gioele",
  "Amos": "Amos",
  "Obadiah": "Abdia",
  "Jonah": "Giona",
  "Micah": "Michea",
  "Nahum": "Naum",
  "Habakkuk": "Abacuc",
  "Zephaniah": "Sofonia",
  "Haggai": "Aggeo",
  "Zechariah": "Zaccaria",
  "Malachi": "Malachia",
  "Matthew": "Matteo",
  "Mark": "Marco",
  "Luke": "Luca",
  "John": "Giovanni",
  "Acts": "Atti",
  "Romans": "Romani",
  "1 Corinthians": "1 Corinzi",
  "2 Corinthians": "2 Corinzi",
  "Galatians": "Galati",
  "Ephesians": "Efesini",
  "Philippians": "Filippesi",
  "Colossians": "Colossesi",
  "1 Thessalonians": "1 Tessalonicesi",
  "2 Thessalonians": "2 Tessalonicesi",
  "1 Timothy": "1 Timoteo",
  "2 Timothy": "2 Timoteo",
  "Titus": "Tito",
  "Philemon": "Filemone",
  "Hebrews": "Ebrei",
  "James": "Giacomo",
  "1 Peter": "1 Pietro",
  "2 Peter": "2 Pietro",
  "1 John": "1 Giovanni",
  "2 John": "2 Giovanni",
  "3 John": "3 Giovanni",
  "Jude": "Giuda",
  "Revelation": "Apocalisse",
  "Prayer": "Preghiera",
  "Traditional Prayer": "Preghiera Tradizionale",
};

export function translateReference(ref: string): string {
  if (!ref) return "";
  // Match "Book Chapter:Verse" pattern
  const match = ref.match(/^(.+?)\s+(\d.*)$/);
  if (!match) {
    // No chapter/verse, just a label like "Prayer"
    return BOOK_MAP[ref] || ref;
  }
  const [, book, chapterVerse] = match;
  const italianBook = BOOK_MAP[book] || book;
  return `${italianBook} ${chapterVerse}`;
}
